### ISSUE TITLE
The mod doesn't work at all.

### ISSUE THREAD

**Issue by Rencer** [TeamElysia/Byte-Drives#2]
I installed the mod and when I look into NEI, to find out the recipes, but there is no recipes.

In the courseforge page you stated:
"Latest release v0.1.0.0 currently only provides the storage aspect of this mod's feature list."

So, it means the mod should work and I can craft those storages, but for me it doesn't do anything.

What is the recipes? Why I find nothing in NEI? Is this mod do anything at all in this early alpha?

**Comment by TheUnknownFew** [comment]
Well, it SHOULD be working and ive tested it, but i am certainly expecting that release to be buggy. Ive not had time to work on it recently because of real life conflicts, but a more stable alpha is in the works for a next release. The first release wasnt intendid to be "playable" but rather for feedback like this. ill look into this issue, but it works on my end. pmease give me more details on the issue if you can. I shall reply with a few recipies to test a bit later.

**Comment by TheUnknownFew** [comment]
So here is a crafting recipe.
https://i.imgur.com/5ObBgdZ.png
Try that to see if it works at all, otherwise I will need more information on why it isnt working, like maybe your FML-CLIENT-LATEST log

**Comment by Rencer** [comment]
I figured out what was the problem.

I craft that recipe and it works.
Switching to default Minecraft crative menu; the recipes are there and working.
I disabled NEI and JEI now shows the recipes and I can search for them, too.
So it's something between NEI and your mod.
Thanks.
